name: "PR Checks"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: "yarn install"
        run: yarn install

      - name: "yarn build"
        run: yarn build

      - name: "check for uncommitted changes"
        # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
        run: |
          git diff --exit-code --stat -- . ':!node_modules' \
          || (echo "##[error] found changed files after build. please 'yarn build && npm run format'" \
                   "and check in all changes" \
              && exit 1)
