name: "Test"
on: [push, pull_request] 

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

    - name: "yarn install"
      run: yarn install

    - name: "yarn test"
      run: yarn test
